In [ ]:
!pip install numpy > 2

In [6]:
import torch
import numpy as np
import time
import torch.nn as nn

device  = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
randint  = torch.randint(-100, 100, (6,))

In [4]:
randint

tensor([ 30,  -9, -76,  74,  52, -85])

In [5]:
type(randint)

torch.Tensor

In [6]:
tensor = torch.tensor([[1.1,2.2],[1.3,4.5],[5.6,9.8]])

In [7]:
tensor

tensor([[1.1000, 2.2000],
        [1.3000, 4.5000],
        [5.6000, 9.8000]])

In [8]:
tensor.shape

torch.Size([3, 2])

In [9]:
type(tensor)


torch.Tensor

In [10]:
tensor.size()

torch.Size([3, 2])

In [11]:
tensor.shape == tensor.size()

True

In [12]:
zeros = torch.zeros(3,2)

In [13]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
print(type(zeros[1,1]))


<class 'torch.Tensor'>


In [15]:
ones = torch.ones(3,4)

In [16]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
input  = torch.empty(1,1)

In [18]:
input

tensor([[1.]])

In [19]:
arange = torch.arange(2,256)

In [20]:
arange

tensor([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 1

In [21]:
linspace = torch.linspace(2,10,steps = 10)

In [22]:
linspace

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])

In [23]:
type(linspace)

torch.Tensor

In [24]:
#linspace is used when you want the constant increment in specific steps in specific range.

In [25]:
logspace = torch.logspace(3,5,8)

In [26]:
logspace

tensor([  1000.0000,   1930.6978,   3727.5938,   7196.8569,  13894.9551,
         26826.9570,  51794.7461, 100000.0000])

In [27]:
eye = torch.eye(5)

In [28]:
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [29]:
empty = torch.empty((3,2), dtype = int)

In [30]:
empty

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [31]:
empty_like = torch.empty_like(empty)


In [32]:
empty_like

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [33]:
type(empty)

torch.Tensor

In [34]:
type(empty_like)

torch.Tensor

In [35]:
start_time = time.time()
zeros = torch.zeros(3,3)
end_time  = time.time()

elapsed_time = end_time-start_time

In [36]:
# print(f"{elapsed_time.4f}")
print(f"{elapsed_time:.4f}")

0.0000


In [37]:
# import torch
# import numpy as np
# import time

# # Check if CUDA is available and set the device accordingly
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# print(f"Device: {device}")

m1 = torch.rand(10, 10, 10, 10).to(device)
m2 = torch.rand(10, 10, 10, 10).to(device)


start = time.time()
m3 = m1 @ m2  
end = time.time()
elapsed = end - start
print(f"Time taken for PyTorch matrix multiplication: {elapsed:.4f} seconds")

start1 = time.time()
m4 = m1*m2
end1 = time.time()
elapsed1 = end1 - start1
print(f"Time taken for NumPy element-wise multiplication: {elapsed1:.4f} seconds")


Time taken for PyTorch matrix multiplication: 1.3801 seconds
Time taken for NumPy element-wise multiplication: 3.1977 seconds


In [38]:
probabilities = torch.tensor([0.1,0.9])

In [39]:
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
tensor = torch.tensor([1,2,3,4])
tensor_ = torch.cat((tensor, torch.tensor([7])), dim = 0)
tensor_

tensor([1, 2, 3, 4, 7])

In [41]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [42]:
out  = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [43]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float(-5))
out

tensor([[ 0., -5., -5., -5., -5.],
        [ 0.,  0., -5., -5., -5.],
        [ 0.,  0.,  0., -5., -5.],
        [ 0.,  0.,  0.,  0., -5.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [44]:
torch.exp(out)

tensor([[1.0000, 0.0067, 0.0067, 0.0067, 0.0067],
        [1.0000, 1.0000, 0.0067, 0.0067, 0.0067],
        [1.0000, 1.0000, 1.0000, 0.0067, 0.0067],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.0067],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])

In [45]:
input = torch.zeros(4,3,2)
input 

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [46]:
out  = input.transpose(0,2)
print(out)
out.shape

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


torch.Size([2, 3, 4])

In [47]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1,2,3])
t3 = torch.tensor([1,2,9])

t4 = torch.stack([t1,t3,t2])
print(t4)
print(t4.shape)
print(t4.type)

tensor([[1, 2, 3],
        [1, 2, 9],
        [1, 2, 3]])
torch.Size([3, 3])
<built-in method type of Tensor object at 0x000002C8A7839550>


In [48]:
import torch.nn as nn
input_ = torch.tensor([10.,10.,10.])
nn_ = nn.Linear(3,3, bias = False )
nn_(input_)

tensor([ 6.7593,  7.3051, -1.6230], grad_fn=<SqueezeBackward4>)

In [49]:
import torch.nn.functional as f
tensor_ = torch.tensor([10, 10., 10.])

s = f.softmax(tensor_, dim = -1)
print(s)


tensor([0.3333, 0.3333, 0.3333])


In [56]:
vocab_size = 80
embedding_dim = 6
embeddings = nn.Embedding(vocab_size,embedding_dim)
# print(embeddings)

input_ = torch.LongTensor([1,5,3,2,8,9])

output = embeddings(input_)

print(output.shape)
print(output)

torch.Size([6, 6])
tensor([[ 0.1648,  0.0166, -0.8359,  0.1642,  1.1018,  0.2074],
        [ 1.4485, -0.0105,  1.0238, -0.8001,  0.4143, -0.2899],
        [ 0.1324,  1.5178,  2.3409, -0.4126, -1.1943,  1.0129],
        [ 0.7365, -0.6354, -0.7299,  0.1036,  0.6750,  0.8347],
        [ 0.7878,  0.3045,  1.5088,  1.6801, -0.2527, -0.4315],
        [ 0.7565, -0.0088, -1.1209, -0.3795,  0.8477, -0.3040]],
       grad_fn=<EmbeddingBackward0>)


In [60]:
int_64 = torch.randint(3, (2,3)).float()
print(int_64)
f = torch.rand(3,2)
print(f)
out = torch.matmul(int_64, f)
print(out)

tensor([[0., 0., 1.],
        [1., 2., 0.]])
tensor([[0.2291, 0.0231],
        [0.7367, 0.3247],
        [0.2251, 0.6668]])
tensor([[0.2251, 0.6668],
        [1.7025, 0.6725]])
